# VIVADO_PROJECT = r"../Lab5v1"
import os.path

VIVADO_PROJECT = os.path.join('..', 'Lab5v1')

ACTIVE_VIDEO_H = 800
FRONT_PORCH_H = 56
SYNC_PULSE_H = 120
BACK_PORCH_H = 64
SIZE_H = ACTIVE_VIDEO_H + FRONT_PORCH_H + SYNC_PULSE_H + BACK_PORCH_H

ACTIVE_VIDEO_V = 600
FRONT_PORCH_V = 37
SYNC_PULSE_V = 6
BACK_PORCH_V = 23
SIZE_V = ACTIVE_VIDEO_V + FRONT_PORCH_V + SYNC_PULSE_V + BACK_PORCH_V
